"""create initial learning schema

Revision ID: 2899ff1d876c
Revises:
Create Date: 2026-07-26 22:11:54.941483

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2899ff1d876c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_topics_slug"), "topics", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("google_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("avatar_url", sa.String(length=2048), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'disabled')", name="users_status_check"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_google_subject"), "users", ["google_subject"], unique=True
    )
    op.create_table(
        "admin_allowlist",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("added_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["added_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_admin_allowlist_email"), "admin_allowlist", ["email"], unique=True
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=100), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sa.Uuid(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("before_data", sa.JSON(), nullable=True),
        sa.Column("after_data", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_request_id"), "audit_logs", ["request_id"], unique=False
    )
    op.create_index(
        "ix_audit_logs_target_created_at",
        "audit_logs",
        ["target_type", "target_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "exams",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exams_slug"), "exams", ["slug"], unique=True)
    op.create_table(
        "exam_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("exam_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("difficulty", sa.String(length=50), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status != 'published') OR published_at IS NOT NULL",
            name="exam_versions_published_at_check",
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'in_review', 'published', 'archived')",
            name="exam_versions_status_check",
        ),
        sa.CheckConstraint("duration_minutes > 0", name="exam_versions_duration_check"),
        sa.CheckConstraint("version_number > 0", name="exam_versions_number_check"),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exam_versions_difficulty"),
        "exam_versions",
        ["difficulty"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exam_versions_exam_id"), "exam_versions", ["exam_id"], unique=False
    )
    op.create_index(
        "ix_exam_versions_published_at",
        "exam_versions",
        ["status", "published_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exam_versions_status"), "exam_versions", ["status"], unique=False
    )
    op.create_index(
        "uq_exam_versions_exam_version",
        "exam_versions",
        ["exam_id", "version_number"],
        unique=True,
    )
    op.create_index(
        "uq_exam_versions_one_published",
        "exam_versions",
        ["exam_id"],
        unique=True,
        postgresql_where=sa.text("status = 'published'"),
    )
    op.create_table(
        "exam_version_topics",
        sa.Column("exam_version_id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exam_version_id"],
            ["exam_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("exam_version_id", "topic_id"),
    )
    op.create_index(
        "uq_exam_version_topics_primary",
        "exam_version_topics",
        ["exam_version_id"],
        unique=True,
        postgresql_where=sa.text("is_primary"),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("exam_version_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.CheckConstraint("position > 0", name="questions_position_check"),
        sa.ForeignKeyConstraint(
            ["exam_version_id"],
            ["exam_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_questions_exam_version_id"),
        "questions",
        ["exam_version_id"],
        unique=False,
    )
    op.create_index(
        "uq_questions_version_position",
        "questions",
        ["exam_version_id", "position"],
        unique=True,
    )
    op.create_table(
        "question_options",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.CheckConstraint("position > 0", name="question_options_position_check"),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_options_question_id"),
        "question_options",
        ["question_id"],
        unique=False,
    )
    op.create_index(
        "uq_question_options_position",
        "question_options",
        ["question_id", "position"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_question_options_position", table_name="question_options")
    op.drop_index(
        op.f("ix_question_options_question_id"), table_name="question_options"
    )
    op.drop_table("question_options")
    op.drop_index("uq_questions_version_position", table_name="questions")
    op.drop_index(op.f("ix_questions_exam_version_id"), table_name="questions")
    op.drop_table("questions")
    op.drop_index(
        "uq_exam_version_topics_primary",
        table_name="exam_version_topics",
        postgresql_where=sa.text("is_primary IS 1"),
    )
    op.drop_table("exam_version_topics")
    op.drop_index(
        "uq_exam_versions_one_published",
        table_name="exam_versions",
        postgresql_where=sa.text("status = 'published'"),
    )
    op.drop_index("uq_exam_versions_exam_version", table_name="exam_versions")
    op.drop_index(op.f("ix_exam_versions_status"), table_name="exam_versions")
    op.drop_index("ix_exam_versions_published_at", table_name="exam_versions")
    op.drop_index(op.f("ix_exam_versions_exam_id"), table_name="exam_versions")
    op.drop_index(op.f("ix_exam_versions_difficulty"), table_name="exam_versions")
    op.drop_table("exam_versions")
    op.drop_index(op.f("ix_exams_slug"), table_name="exams")
    op.drop_table("exams")
    op.drop_index("ix_audit_logs_target_created_at", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_request_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_admin_allowlist_email"), table_name="admin_allowlist")
    op.drop_table("admin_allowlist")
    op.drop_index(op.f("ix_users_google_subject"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_topics_slug"), table_name="topics")
    op.drop_table("topics")
    # ### end Alembic commands ###
